ext {
    var = 'key0'
}// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    ext {
        agp_version = '5.1.0'
        agp_version1 = '8.5.1'
        agp_version2 = '4.2.1'
    }
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath "com.android.tools.build:gradle:$agp_version2"
        classpath 'com.google.gms:google-services:4.3.15'
        classpath "com.github.dcendents:android-maven-gradle-plugin:2.0"
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }

        jcenter()

        maven { url 'https://jitpack.io' }
        maven { url "https://oss.jfrog.org/artifactory/oss-snapshot-local" }

        maven { url 'https://jitpack.io' }
        mavenCentral()

        maven { url 'https://jitpack.io' }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}